version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "
        bundle install &&
        rm -f tmp/pids/server.pid &&
        yarn install &&
        ./bin/dev
      "
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  postgres_volume:
